apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: wordpress

---
apiVersion: v1
kind: Secret
metadata:
  name: wp-db-secrets
  namespace: wordpress
type: Opaque
data:
  MYSQL_PASSWORD: d29yZHByZXNz

---

apiVersion: v1
kind: Secret
metadata:
  name: wp-db-user
  namespace: wordpress
type: Opaque
data:
  MYSQL_USER: d29yZHByZXNz

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  storageClassName: local-storage
  claimRef:
    name: mysql-volume
    namespace: wordpress
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /mnt
  nodeAffinity:
   required:
    nodeSelectorTerms:
    - matchExpressions:
      - key: kubernetes.io/hostname
        operator: In
        values:
        - worker1

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-volume
  namespace: wordpress
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: wordpress
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: database
        image: mariadb:10.6.4-focal
        args:
          # mount volume
          - "--default-authentication-plugin=mysql_native_password"
        # add root password
        env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wp-db-secrets
                  key: MYSQL_PASSWORD
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wp-db-secrets
                  key: MYSQL_PASSWORD
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: wp-db-user
                  key: MYSQL_USER
            - name: MYSQL_DATABASE
              value: wordpress
          
        ports:
          - containerPort: 3306
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-volume
---


apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: wordpress
spec:
  ports:
  - port: 3306
    protocol: TCP
  selector:
    app: mysql

---



